# Generated by Django 5.2.4 on 2025-07-11 07:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoProcessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("youtube_url", models.URLField(max_length=500)),
                ("clip_duration", models.IntegerField(help_text="Duration in seconds")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ViralClip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_timestamp",
                    models.FloatField(help_text="Start time in seconds"),
                ),
                ("end_timestamp", models.FloatField(help_text="End time in seconds")),
                (
                    "justification",
                    models.TextField(help_text="Why this moment is viral"),
                ),
                ("emotional_keywords", models.JSONField(blank=True, default=list)),
                ("urgency_indicators", models.JSONField(blank=True, default=list)),
                (
                    "virality_score",
                    models.IntegerField(
                        blank=True, help_text="Score from 0-100", null=True
                    ),
                ),
                ("clip_url", models.URLField(blank=True, max_length=500, null=True)),
                ("preview_url", models.URLField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "video_processing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clips",
                        to="core.videoprocessing",
                    ),
                ),
            ],
            options={
                "ordering": ["-virality_score", "-created_at"],
            },
        ),
    ]
